FROM nginx:1.18
ARG DIST_DIR=dist
ENV USER_NAME=user01
ENV USER_ID=70007
ENV GROUP_NAME=group01
ENV USER_HOME=/home/user01
ENV APP_HOME=APP1
RUN groupadd-g $GROUP_ID $GROUP_NAME && useradd -u $USER_ID -M -D $USER_HOME --SHELL/bin/bash -g $GROUP _NAME $USER_NAME
RUN mkdir -p $APP_HOME &&MKDIR-P $APP_HOME/bin/nginx/html && mkdir -p  $APP_HOME/log  && mkdir -p $APP_HOME/data && mkdir -p $APP_HOME/job && chown -R $USER_NAME:$GROUP_NAME
RUN addgroup $USER_NAME root
ADD $\{DIST_DIR\} /appl/bin/nginx/html
ADD docker/default.conf/etc/nginx/conf.d/default.conf
ADD docker/error.html  /usr/share/nginx/html/error.html
RUN chmod  -R 775 $APP_HOME
RUN chmod g+rwx  /var/cache/nginx  /var/run /log/nginx
 # comment user directive
RUN sed -i.bak  *s/^user/#user/' /etc/nginx/nginx.conf

#RUN chmod +x DOCKERENTRYPOINT.sh
RUN chown  -R $USER-NAME:$GROUP_NAME $APP_HOME && CHMOD -R 775 $APP_HOME 
USER $USER_NAME
WORKDIR $APP_HOME/bin
CMD [''/usr/sbin/nginx'',  "-g'',  ''daemon off;'']